### ISSUE TITLE
interface conversi on: interface {} is nil, not *v1.Pod)

### ISSUE THREAD

**Issue by valentin2105** [lnsp/k8s-crash-informer#1]
Hi,

I got an issue while giving a try to k8s-mattermost-informer, 

```
I0225 04:53:30.082713       1 controller.go:146] Pod default/mattermost-informer-6c8d7c694d-w5z4g does not exist anymor
e
E0225 04:53:30.082942       1 runtime.go:69] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(
0x11919a0), concrete:(*runtime._type)(nil), asserted:(*runtime._type)(0x12f0e00), missingMethod:""} (interface conversi
on: interface {} is nil, not *v1.Pod)
/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/runtime/iface.go:248
/go/src/github.com/lnsp/mattermost-informer/pkg/controller/controller.go:148
/go/src/github.com/lnsp/mattermost-informer/pkg/controller/controller.go:57
/go/src/github.com/lnsp/mattermost-informer/pkg/controller/controller.go:208
/go/src/github.com/lnsp/mattermost-informer/pkg/controller/controller.go:200
/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152
/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153
/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1333
panic: interface conversion: interface {} is nil, not *v1.Pod [recovered]
        panic: interface conversion: interface {} is nil, not *v1.Pod

goroutine 24 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x11c5080, 0xc0006d5320)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/lnsp/mattermost-informer/pkg/controller.(*Controller).syncToStdout(0xc0006f0370, 0xc0006703f0, 0x2c, 0x11543
20, 0xc000363ee0)
        /go/src/github.com/lnsp/mattermost-informer/pkg/controller/controller.go:148 +0x3a0
github.com/lnsp/mattermost-informer/pkg/controller.(*Controller).processNextItem(0xc0006f0370, 0xc0006de100)
        /go/src/github.com/lnsp/mattermost-informer/pkg/controller/controller.go:57 +0xd3
github.com/lnsp/mattermost-informer/pkg/controller.(*Controller).runWorker(0xc0006f0370)
        /go/src/github.com/lnsp/mattermost-informer/pkg/controller/controller.go:208 +0x2b
github.com/lnsp/mattermost-informer/pkg/controller.(*Controller).runWorker-fm()
        /go/src/github.com/lnsp/mattermost-informer/pkg/controller/controller.go:200 +0x2a
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000534040)
        /go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000534040, 0x3b9aca00, 0x0, 0x1, 0xc00009c240)
        /go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xbe
k8s.io/apimachinery/pkg/util/wait.Until(0xc000534040, 0x3b9aca00, 0xc00009c240)
        /go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/lnsp/mattermost-informer/pkg/controller.(*Controller).Run
        /go/src/github.com/lnsp/mattermost-informer/pkg/controller/controller.go:200 +0x1cb

```

Any idea of what happend  ? 

I use k8s v1.12.3, in IPv6. but it doesn't seem to be the issue.

Thanks !

**Comment by lnsp** [comment]
Thank you for your feedback! It seems that Docker Hub did not have the latest version in stock yet, it should be fixed now.

**Comment by valentin2105** [comment]
Hi,

Thanks, it seem to not crash anymore, but strangly, I didn't receive any message in Mattermost, without any error in the pod logs. 

( I have kill a pod that run in same namespace few time, it detect the deletion, but don't send any notification, and the deployment is correctly annotated to `inform`).

**Comment by lnsp** [comment]
Remember that you need to annotate the pod directly, so the `template/spec` section in your deployment needs to have the annotation not the deployment itself.

I still work on getting annotated deployments working.

**Comment by valentin2105** [comment]
@lnsp  
I have correctly annotated the pod : 

```
{
  "apiVersion": "v1",
  "kind": "Pod",
  "metadata": {
    "annotations": {
      "espe.tech/mattermost": "inform",
      "kubernetes.io/egress-bandwidth": "1M",
      "kubernetes.io/ingress-bandwidth": "1M"
    },
    "creationTimestamp": "2019-02-26T23:52:45Z",
    "generateName": "toolbox-68b778fd97-",

```
And when I delete it, I got few logs : 

```
I0226 23:53:50.422832       1 controller.go:144] Received create/update/delete for Pod default/toolbox-68b778fd97-swvd2
I0226 23:54:19.654445       1 controller.go:144] Received create/update/delete for Pod default/toolbox-68b778fd97-qjprz
I0226 23:54:29.121089       1 controller.go:144] Received create/update/delete for Pod default/toolbox-68b778fd97-qjprz
I0226 23:54:29.125683       1 controller.go:138] Pod default/toolbox-68b778fd97-qjprz does not exist anymore 

```

But not any message in Mattermost of error for sending the message.

Any idea ? 

Thanks.

**Comment by lnsp** [comment]
Oh, now I get it. If you delete it, nothing will be reported (because I assume if you delete a pod its good behavior). It only reports when a pod continously crashes (like when a service dependency is down etc.). The crash must come from the container itself.

**Comment by valentin2105** [comment]
Ok great I understand ! 

Thanks I will try to crash my pods. 

It would be aweome to notify if the pod moved in Not Ready state (0/1) READY. 

:+1:
